name: "disperse-validate"
branding:
  color: red
  icon: package
description: >
  Validate a disperse config
inputs:
  path:
    description: >
      Set disperse file path to check
    required: false
runs:
  using: 'docker'
  image: 'docker://ghcr.io/jelmer/action-disperse-validate:2.0.1'
  args:
    - ${{ inputs.path }}
